.\" Copyright 2023 IBM Corp.
.\" s390-tools is free software; you can redistribute it and/or modify
.\" it under the terms of the MIT license. See LICENSE for details.
.\"

.TH pvsecret-lock 1 "2024-01-30" "s390-tools" "UV-Secret Manual"
.nh
.ad l
.SH NAME
\fBpvsecret lock\fP - Lock the secret-store (s390x only)
\fB
.SH SYNOPSIS
.nf
.fam C
pvsecret lock
.fam C
.fi
.SH DESCRIPTION
Lock the secret store (s390x only). After this command executed successfully,
all add-secret requests will fail. Only available on s390x.
.SH "SEE ALSO"
.sp
\fBpvsecret\fR(1)
