.\" Copyright 2023, 2024 IBM Corp.
.\" s390-tools is free software; you can redistribute it and/or modify
.\" it under the terms of the MIT license. See LICENSE for details.
.\"

.TH "PVSECRET-LIST" "1" "2024-12-19" "s390-tools" "UV-Secret Manual"
.nh
.ad l
.SH NAME
pvsecret-list \- List all ultravisor secrets (s390x only)
.SH SYNOPSIS
.nf
.fam C
pvsecret list [OPTIONS] [FILE]
.fam C
.fi
.SH DESCRIPTION
Lists the IDs of all non\-null secrets currently stored in the ultravisor for
the currently running IBM Secure Execution guest. Only available on s390x.
.SH OPTIONS
.PP
<FILE>
.RS 4
Store the result in FILE.
[default: '-']
.RE
.RE

.PP
\-\-format <FORMAT>
.RS 4
Define the output format of the list.
[default: 'human']

Possible values:
.RS 4
\- \fBhuman\fP: Human-focused, non-parsable output format.

\- \fByaml\fP: Use yaml format.

\- \fBbin\fP: Use the format the ultravisor uses to pass the list.

.RE
.RE
.PP
\-h, \-\-help
.RS 4
Print help (see a summary with \fB\-h\fR).
.RE
.RE

.SH "SEE ALSO"
.sp
\fBpvsecret\fR(1)
