.\" Copyright 2024 IBM Corp.
.\" s390-tools is free software; you can redistribute it and/or modify
.\" it under the terms of the MIT license. See LICENSE for details.
.\"

.TH "PVSECRET-LOCK" "1" "2024-12-19" "s390-tools" "UV-Secret Manual"
.nh
.ad l
.SH NAME
pvsecret-lock \- Lock the secret-store (s390x only)
.SH SYNOPSIS
.nf
.fam C
pvsecret lock
.fam C
.fi
.SH DESCRIPTION
Lock the secret store (s390x only). After this command executed successfully,
all subsequent add\-secret requests will fail. Only available on s390x.
.SH "SEE ALSO"
.sp
\fBpvsecret\fR(1)
