.\" Copyright 2023 IBM Corp.
.\" s390-tools is free software; you can redistribute it and/or modify
.\" it under the terms of the MIT license. See LICENSE for details.
.\"

.TH pvsecret-version 1 "2023-07-28" "s390-tools" "UV-Secret Manual"
.nh
.ad l
.SH NAME
\fBpvsecret version\fP- Print version information and exit
\fB
.SH SYNOPSIS
.nf
.fam C
pvsecret version
.fam C
.fi
.SH DESCRIPTION
Print version information and exit

.SH OPTIONS

.SH "SEE ALSO"
.sp
\fBpvsecret\fR(1)
