.\" Copyright 2023 IBM Corp.
.\" s390-tools is free software; you can redistribute it and/or modify
.\" it under the terms of the MIT license. See LICENSE for details.
.\"

.TH pvsecret-add 1 "2023-10-09" "s390-tools" "UV-Secret Manual"
.nh
.ad l
.SH NAME
\fBpvsecret add\fP - Perform an add-secret request (s390x only)
\fB
.SH SYNOPSIS
.nf
.fam C
pvsecret add <FILE>
.fam C
.fi
.SH DESCRIPTION
Perform an add-secret request using a previously generated add-secret request.
Only available on s390x.
.SH OPTIONS
.PP
<FILE>
.RS 4
Specify the request to be sent.
.RE
.RE


.SH "SEE ALSO"
.sp
\fBpvsecret\fR(1)
