.\" Copyright 2024 IBM Corp.
.\" s390-tools is free software; you can redistribute it and/or modify
.\" it under the terms of the MIT license. See LICENSE for details.
.\"

.TH "PVSECRET-RETRIEVE" "1" "2024-12-19" "s390-tools" "UV-Secret Manual"
.nh
.ad l
.SH NAME
pvsecret-retrieve \- Retrieve a secret from the UV secret store (s390x only)
.SH SYNOPSIS
.nf
.fam C
pvsecret retrieve [OPTIONS] <ID>
pvsecret retr [OPTIONS] <ID>
.fam C
.fi
.SH DESCRIPTION
Retrieve a secret from the UV secret store (s390x only)
.SH OPTIONS
.PP
<ID>
.RS 4
Specify the secret ID to be retrieved. Input type depends on \fB\-\-inform\fR.
If `yaml` (default) is specified, it must be a yaml created by the create
subcommand of this tool. If `hex` is specified, it must be a hex 32\-byte
unsigned big endian number string. Leading zeros are required.
.RE
.RE

.PP
\-o, \-\-output <FILE>
.RS 4
Specify the output path to place the secret value.
[default: '-']
.RE
.RE
.PP
\-\-inform <INFORM>
.RS 4
Define input type for the Secret ID.
[default: 'yaml']

Possible values:
.RS 4
\- \fByaml\fP: Use a yaml file.

\- \fBhex\fP: Use a hex string.

\- \fBname\fP: Use a name-string. Will hash it if no secret with the name found.

.RE
.RE
.PP
\-\-outform <OUTFORM>
.RS 4
Define the output format for the retrieved secret.
[default: 'pem']

Possible values:
.RS 4
\- \fBpem\fP: Write the secret as PEM.

\- \fBbin\fP: Write the secret in binary.

.RE
.RE
.PP
\-h, \-\-help
.RS 4
Print help (see a summary with \fB\-h\fR).
.RE
.RE

.SH "SEE ALSO"
.sp
\fBpvsecret\fR(1)
