#!/bin/bash
#
# FCP adapter trace utility
#
# Script to collect all system information required for analysis
#
# Copyright IBM Corp. 2008, 2017
# Copyright Red Hat Inc. 2017
#
# s390-tools is free software; you can redistribute it and/or modify it under
# the terms of the MIT license. See LICENSE for details

function version {
	echo "$PROGRAM_NAME: version %S390_TOOLS_VERSION%"
	echo "Copyright IBM Corp. 2008, 2017"
	echo "Copyright Red Hat Inc. 2017"
}

function usage {
	cat <<EOD
Usage: $PROGRAM_NAME [<options>]

$PROGRAM_NAME collects all system information required for analysis.

Options:
	-h, --help
		print this help text and exit.

	-v, --version
		print version information and exit.

	-o, --output
		specify the name of the output file
EOD
}

function store_mapper_devices {
	dest_dir="$1"
	src_dir="$2"

	for i in `ls $src_dir`; do
		mm=$(stat -L -c%t:%T $src_dir/$i)
		m1=$(echo "$mm" | cut -f1 -d':')
		m2=$(echo "$mm" | cut -f2 -d':')
		printf "%d:%d" 0x$m1 0x$m2 > $dest_dir/$src_dir/$i
	done
}

PROGRAM_NAME="$(basename $0)"
OUT_FILE="config"
TMP_DIR=$(mktemp -d tmp.XXXXXX)

function cleanup {
	rm -rf $TMP_DIR
}

trap cleanup EXIT

while [[ $# -gt 0 ]]; do
	key="$1"

	case $key in
		-v|--version)
			version
			exit 0
		;;
		-h|--help)
			usage
			exit 0
		;;
		-o|--output)
			OUT_FILE="$2"
			shift
			shift
		;;
		*)
			echo "Invalid usage !"
			usage
			exit 1
		;;
	esac
done

mkdir -p $TMP_DIR/sys/block $TMP_DIR/sys/devices/virtual/block \
	$TMP_DIR/sys/class $TMP_DIR/dev/mapper
rsync -a --inplace /sys/block/dm* /sys/block/sd* $TMP_DIR/sys/block 2>/dev/null
rsync -a --inplace --exclude=chpd* /sys/devices/css0 \
	$TMP_DIR/sys/devices 2>/dev/null
rsync -a --inplace /sys/devices/virtual/block/dm* \
	$TMP_DIR/sys/devices/virtual/block 2>/dev/null
rsync -a --inplace /sys/class/fc_host /sys/class/scsi_device \
	/sys/class/scsi_tape /sys/class/scsi_generic \
	/sys/class/fc_remote_ports $TMP_DIR/sys/class 2>/dev/null
store_mapper_devices $TMP_DIR "/dev/mapper"
tar -czf $OUT_FILE.cfg -C $TMP_DIR sys dev 2>/dev/null

exit 0
