.\" Copyright 2017 IBM Corp.
.\" s390-tools is free software; you can redistribute it and/or modify
.\" it under the terms of the MIT license. See LICENSE for details.
.\"
.TH LSCHP 8 "Jul 2012" s390\-tools

.SH NAME
lsscm \- list information about available Storage Class Memory Increments.

.SH SYNOPSIS
.B lsscm
.RB [ \-h|\-\-help ]
.RB [ \-v|\-\-version ]

.SH DESCRIPTION
The lsscm command lists status and information about available
Storage Class Memory Increments.

.B Column description:

SCM Increment
.RS
Starting address of the SCM increment.
.RE

Size
.RS
Size of the block device representing the SCM increment.
.RE

Name
.RS
Name of the block device representing the SCM increment.
.RE

Rank
.RS
Rank (conceptual quality) of the SCM increment.
.RE

D_state
.RS
Data state of the SCM increment.
.RE

O_state
.RS
Operation state of the SCM increment.
.RE

Pers
.RS
Persistence attribute.
.RE

ResID
.RS
Resource identifier.
.RE


.SH OPTIONS
.B \-h | \-\-help
.RS
Print a short help text, then exit.
.RE

.B \-v | \-\-version
.RS
Print version number, then exit.
.RE
