.\" Copyright IBM Corp.
.\" s390-tools is free software; you can redistribute it and/or modify
.\" it under the terms of the MIT license. See LICENSE for details.
.\"

.TH "PVATTEST-PERFORM" "1" "2026-08-11" "s390-tools" "Attestation Manual"
.nh
.ad l
.SH "NAME"
pvattest-perform \- Send the attestation request to the Ultravisor (s390x only.)
.SH "SYNOPSIS"
.nf
.fam C
\fBpvattest\fR \fBperform\fR [OPTIONS] [IN] [OUT]
.fam C
.fi
.SH "DESCRIPTION"
Run a measurement of this system through \fB/dev/uv\fR. This device must be
accessible and the attestation Ultravisor facility must be present. The input
must be an attestation request created with \fBpvattest create\fR. Output will
contain the original request and the response from the Ultravisor. Only
available on s390x.
.SH "OPTIONS"
<IN>
.RS 4
Specify the request to be sent.
.RE
.PP
<OUT>
.RS 4
Write the result to FILE.
.RE
.PP
\-i, \-\-input <FILE>
.RS 4
Specify the request to be sent.
.RE
.PP
\-o, \-\-output <FILE>
.RS 4
Write the result to FILE.
.RE
.PP
\-u, \-\-user\-data <File>
.RS 4
Provide up to 256 bytes of user input

User\-data is arbitrary user\-defined data appended to the Attestation
measurement. It is verified during the Attestation measurement verification. May
be any arbitrary data, as long as it is less or equal to 256 bytes
.RE
.PP
\-h, \-\-help
.RS 4
Print help (see a summary with \fB\-h\fR).
.RE
.SH "EXAMPLES"
Perform an attestation measurement with the attestation request 'attreq.bin' and write the output to 'attresp.bin'.
.PP
.nf
.fam C
       $ pvattest perform attreq.bin attresp.bin


.fam T
.fi
.SH "SEE ALSO"
\fBpvattest\fR(1)