# Common definitions
include ../../common.mak

all:

install:
	$(INSTALL) -d -m 755 $(DESTDIR)$(MANDIR)/man8
	$(INSTALL) -m 644 -c genprotimg.8 $(DESTDIR)$(MANDIR)/man8

clean:

.PHONY: all install clean
