# Common definitions
include ../../common.mak

all:

install:
	$(INSTALL) -d -m 755 $(DESTDIR)$(MANDIR)/man1
	$(INSTALL) -m 644 -c genprotimg.1 $(DESTDIR)$(MANDIR)/man1

clean:

.PHONY: all install clean
