# Common definitions
include ../../common.mak

all:

install:
	$(INSTALL) -d -m 755 $(DESTDIR)$(MANDIR)/man8
	$(INSTALL) -m 644 -c chzdev.8 $(DESTDIR)$(MANDIR)/man8
	$(INSTALL) -m 644 -c lszdev.8 $(DESTDIR)$(MANDIR)/man8

clean:

.PHONY: all clean
