.TH DBGINFO.SH  1 "April 2021" "s390-tools"

.SH NAME
dbginfo.sh \- collect runtime, configuration and trace information
for debugging Linux on IBM Z

.SH SYNOPSIS
.br
\fBdbginfo.sh\fP [OPTIONS]
.br
\fBdbginfo.sh\fP {\-h|\-v}

.SH DESCRIPTION
This script collects runtime, configuration and trace information that can
be used to debug a Linux on IBM Z instance.
For Linux on z/VM, the script also traces information about the z/VM system.
The debug information is written to a file
/tmp/DBGINFO\-<date>\-<time>\-<hostname>\-<processorid>.tgz
where [date] and [time] are the date and time when the debug data was
collected. [hostname] indicates the hostname of the system the data was
collected from. The [processorid] is taken from the processor 0 and indicates
the processor identification.

.SH OPTIONS
.TP
\fB\-h\fP, \fB\-\-help\fP
Print usage information, then exit.

.TP
\fB\-v\fP, \fB\-\-version\fP
Print version information, then exit.

.TP
\fB\-d <DIRECTORY>\fP, \fB\-\-directory <DIRECTORY>\fP
Specify the DIRECTORY where the data collection stores the temporary data and the final archive. The specified directory must already exist. If this parameter is not specified, /tmp is used by default.

.SH FILES
A .tgz file of the form
.PP
.nf
.fam C
    DBGINFO\-<year>\-<month>\-<day>\-<hours>\-<minutes>\-<seconds>\-<hostname>\-<processorid>.tgz

.fam T
.fi
is generated and placed in the /tmp directory or in the directory specified by the -d option.

.SH EXAMPLE
Sample invocation:
.P
[root@host]# dbginfo.sh \-d /data\-collection
.br
dbginfo.sh: Debug information script version %S390_TOOLS_VERSION%
.br
Copyright IBM Corp. 2002, 2021
.PP
Hardware platform     = s390x
.br
Kernel version        = 5.4.0 (5.4.0-70-generic)
.br
Runtime environment   = z/VM
.PP
1 of 16: Collecting command output
.PP
2 of 16: Collecting z/VM command output
.PP
3 of 16: Collecting procfs
.PP
4 of 16: Collecting sysfs
.PP
5 of 16: Collecting log files
.PP
6 of 16: Collecting config files
.PP
7 of 16: Collecting osa oat output
.PP
8 of 16: Collecting ethtool output
.PP
9 of 16: Collecting tc output
.PP
10 of 16: Collecting bridge output
.PP
11 of 16: Collecting OpenVSwitch output
.PP
12a of 16: Collecting docker container
12b of 16: Collecting docker network
.PP
13 of 16: Collecting nvme output
.PP
14 of 16: Collecting KVM data
.PP
15 of 16: Postprocessing
.PP
16 of 16: Finalizing: Creating archive with collected data
.PP
Collected data was saved to:
.br
 >>  /data\-collection/DBGINFO\-2021\-04\-20\-14\-00\-07\-host\-012345.tgz  <<
.br
Review the collected data before sending to your service organization.
.SH HINTS
Run the script with root authority.
.br
For Linux on z/VM, only z/VM guest virtual machines with class B privileges
yield the complete debug information.
.SH AUTHOR
Linux on IBM Z development <linux390@de.ibm.com>
