.TH ZIPL-SWITCH-TO-BLSCFG  1 "April 2018" "s390-tools"

.SH NAME
zipl-switch-to-blscfg \- Switch zipl to use BootLoaderSpec configuration

.SH SYNOPSIS
.br
\fBzipl-switch-to-blscfg\fP [OPTIONS]
.br
\fBzipl-switch-to-blscfg\fP {\-h|\-v}

.SH DESCRIPTION
This script switches the zipl boot-loader configuration to use BootLoaderSpec
files to define IPL sections. For each Linux kernel defined in the zipl.conf
config file, a BLS fragment is generated in the BLS directory specified. Also,
zipl.conf is modified to only contain global configuration. All IPL sections
come from BLS files.

.SH OPTIONS
.TP
\fB\-h\fP, \fB\-\-help\fP
Print this help and exit

.TP
\fB\-v\fP, \fB\-\-version\fP
Print version information and exit

.TP
\fB\-\-backup-suffix <SUFFIX>\fP
The suffix used for backup files, defaults to .bak.

.TP
\fB\-\-bls-directory <DIRECTORY>\fP
The DIRECTORY where the BLS fragments will be stored. The directory is
created if it does not exist. By default /boot/loader/entries is used.

.TP
\fB\-\-config-file <FILE>\fP
The FILE used for zipl configuration file, defaults to /etc/zipl.conf.

.TP
\fB\-\-ignore-default\fP
Ignore the default option from the zipl configuration file

.TP
\fB\-\-use-version-name\fP
Use the section kernel version as the BLS file name
