.\" Copyright 2017 IBM Corp.
.\" s390-tools is free software; you can redistribute it and/or modify
.\" it under the terms of the MIT license. See LICENSE for details.
.\"
.TH DASDSTAT 8 "Feb 2011" "s390-tools"

.SH NAME
dasdstat \- read or modify the statistics of the DASD device driver.

.SH SYNOPSIS
.TP 8
.B dasdstat
.RB [ \-h ]
.TP 8
.B dasdstat
.RB [ \-e ]
.RB [ \-d ]
.RB [ \-r ]
.RB [ \-i ]
.RB [ \-l ]
.RB [ \-c ]
.RB [ \-w ]
.RB [ \-V ]
.RB [ \-v ]
.RI [ <statistic> " [" <statistic> "] ...]]"

.SH DESCRIPTION
The dasdstat command provides easy access to the debugfs based
statistics of the DASD device driver.

The DASD statistics feature allows one to gather statistical data for
the I/O requests processed by the DASD device driver. This data can be
collected for individual DASD CCW devices (including PAV base and
alias devices), DASD block devices, or globally for all requests
handled by the DASD device driver.

When no other options are specified, then the default operation is to
print the statistics data in a formatted table. When no specific list
of statistics is given, then the operation will be performed on all
available statistics.

.SH OPTIONS
.TP 8
.BR \-h | \-\-help
Print help text.
.TP
.BR \-e | \-\-enable
Enable the statistics.
.TP
.BR \-d | \-\-disable
Disable the statistics.
.TP
.BR \-r | \-\-reset
Reset the statistics.
.TP
.BR \-i | \-\-directory
Specify the directory in which the statistics can be found.
.TP
.BR \-l | \-\-long
Print more detailed information, e.g differentiate between read and
write requests.
.TP
.BR \-c | \-\-columns " \fI<number>\fR"
Format the output in a table with the given number of columns.
.TP
.BR \-w | \-\-column\-width " \fI<width>\fR"
Set the minimum width of the columns in the output table.
.TP
.BR \-V | \-\-verbose
Print more verbose information.
.TP
.BR \-v | \-\-version
Print the version of the s390-tools package and the command.
.TP
\fB<statistic>\fR =
Name of a statistic that the command should work on.

.SH EXAMPLES
\fBdasdstat\fR
.RS
Print a statistics table for each enabled statistic.
.RE

\fBdasdstat \-e\fR
.RS
Enable all DASD statistics.
.RE

\fBdasdstat \-l dasda 0.0.1800 0.0.18fe 0.0.18ff\fR
.RS
Print a detailed statistics table for DASD block device dasda and CCW
devices 0.0.1800, 0.0.18fe and 0.0.18ff. A typical scenario for this
example would be that dasda is the block device that belongs to
PAV base device 0.0.1800, and CCW devices 0.0.18fe and 0.0.18ff are the
associated alias devices.
.RE

.SH AUTHOR
.nf
This man-page was written by Stefan Weinhuber <wein@de.ibm.com>.
.fi
