.\" Copyright 2017, 2018 IBM Corp.
.\" s390-tools is free software; you can redistribute it and/or modify
.\" it under the terms of the MIT license. See LICENSE for details.
.\"
.TH LSTAPE 8 "Jun 2018" "s390-tools"

.SH NAME
lstape \- list tape devices.

.SH SYNOPSIS
.TP 16
.B lstape
.RB [ -h | --help]
.RB [ --scsi-only | --ccw-only ]
.RB [ -v | --version ]
.RB [ -V | --verbose ]
.br
.RB [ --online | --offline ]
.RB [ -s ]
.br
.RB [ -t
.IR <device-type> [, <device-type> ] "" ...]
.br
.RI [ <device-bus-ID> ...]

.SH DESCRIPTION
The lstape command lists all available tape devices on the current host. For
channel attached tape devices this output is the same as the contents of
/proc/tapedevices (which is obsolete) but also includes offline devices. By
default all tape devices are displayed.

The lstape command without the --ccw-only option causes extra SAN traffic
for each SCSI tape or changer device by invoking the sg_inq command.

.SH OPTIONS
.TP 8
\fB-h\fR or \fB--help\fR
Print help text.

.TP 8
\fB-v\fR or \fB--version\fR
Print the version of the s390-tools package and the command.

.TP
\fB-V\fB or \fB--verbose\fR
Adds additional information that does not fit into a single line of output.
This is currently only used for SCSI devices.

.TP
.BR --scsi-only | --ccw-only
Limit output to either SCSI or channel attached tape devices. The output without
SCSI devices is the same as it was with previous versions of this command.

.TP
.BR -s | --shortid
Using this option will list only tape devices that are in channel subsystem 0,
with subchannel set 0. All other devices will be suppressed and the leading
"0.0." for bus IDs of the remaining devices will be removed.
Since this is specific to CCW devices this option has no effect on the output
of SCSI tape devices.

.TP
.BR --online | --offline
Limit output to either online or offline devices. This filter has no effect
on the output of SCSI devices.

.TP
.BR -t | --type " \fI<device-type>\fR"
Limit output to given device types, for example 3490
(currently only applies to channel-attached
tape devices).

.TP
.I <device-bus-ID>
Limits the output to information about the specified tape device or
devices only. For CCW-attached devices only.

.SH OUTPUT FIELDS FOR SCSI TAPE/CHANGER DEVICES
.TP
.B Generic
SCSI generic device file for the tape drive, for example /dev/sg0.
"N/A" if the SCSI generic (sg) kernel functionality is not available.
.TP
.B Device
Main character device node file for accessing the tape drive or medium changer.
SCSI tape devices are only visible if they are known to the SCSI layer. There
are at least two possible drivers that can claim a SCSI tape device. The
lstape command tries to determine the device driver. For the generic tape
and changer driver the device names start with "st" or "sch", while for the
IBM tape driver this would be "IBMtape" or "IBMchanger". If "N/A" is shown,
the device driver could not be determined.
.TP
.B Target
Linux SCSI device name in H:C:T:L format.
.TP
.B Vendor
The vendor field from the SCSI device.
.TP
.B Model
The model field from the SCSI device.
.TP
.B Type
"tapedrv" for a tape drive or "changer" for a medium changer.
.TP
.B State
The state of the SCSI device object in the kernel.
Any state other than "running" can indicate problems.

.PP

For SCSI devices, the --verbose option additionally displays:
.TP
.B HBA
The device bus-ID of the FCP device
through which the tape drive is attached.
"N/A" if device is not attached through zfcp.
.TP
.B WWPN
The WWPN (worldwide port name) of the tape drive in the SAN.
"N/A" if device is not attached through zfcp.
.TP
.B Serial
The serial number.
"NO/INQ" if there is no sg_inq command available.
"NO/SG" if no SCSI generic (sg) kernel support is available.

.SH EXAMPLES
\fBlstape\fR
.RS
List all tape devices that are available 
.RE

\fBlstape --ccw-only -t 3490 --online\fR
.RS
Show all 3490 CCW devices that are online.
.RE

\fBlstape --scsi-only --verbose\fR
.RS
Show all SCSI tape or changer devices with maximum information.
.RE
