#!/bin/bash
#
# znetcontrolunits - define some common control unit mappings
#
# This definitions are not intended to be used as standalone tool, but should be
# used from other tools like a library. E.g. znetconf is one exploiter
# of them.
#
# Copyright IBM Corp. 2008, 2017
#
# s390-tools is free software; you can redistribute it and/or modify
# it under the terms of the MIT license. See LICENSE for details.
#

# The arrays (among other things) should be adapted, if any of those device
# drivers start supporting different CU types/models.

readonly -a CU=(
    1731/01
    1731/05
    3088/08
    3088/1f
    3088/1e
    3088/60
    1731/02
    1731/02
)
#   1731/06 (OSN) is no longer supported
